# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 杰风居
subtitle: 风无所居，杰行天下
description: Android探索者
author: 冯建
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.jayfeng.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 7
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

baidu_analytics: feb5f5f79310346f22b48370584403b1
duoshuo_shortname: jayfeng

# title, chinese available
links_title: Android参考链接
# links
links:
    51VPN: http://go.to51.net/34750
    DevTools: http://androiddevtools.cn/
    干货集中营 : http://gank.io/
    秋百万: http://liaohuqiu.net/
    代码家: http://blog.daimajia.com/
    Drakeet博客: https://drakeet.me/
    Android笔记: http://www.race604.com/
    Gracker: http://www.androidperformance.com/
    OasisFeng: http://blog.oasisfeng.com/
    Android周报: http://www.androidweekly.cn/
    技术小黑屋: http://droidyue.com/
    Trinea: http://www.trinea.cn/
    Fulgens: http://www.easydone.cn/
    程序亦非猿: http://yifeiyuan.me/
    某学姐: http://mouxuejie.com/
    郭霖的专栏: http://blog.csdn.net/guolin_blog
    任玉刚: http://blog.csdn.net/singwhatiwanna
    CodeKK: http://www.codekk.com
    Arsenal: http://android-arsenal.com/
    Stormzhang: http://stormzhang.com/
    张明云: http://zmywly8866.github.io/
    张涛: http://www.kymjs.com/
    朱罗锋: http://www.feeyan.cn/
    杨辉: http://yanghui.name/
    翟一帆: http://blog.zhaiyifan.cn/
    泡在网上日子: http://www.jcodecraeer.com/
    鲍永章: http://baoyz.com/
    吴小龙: http://wuxiaolong.me/
    梦想特工队: http://www.wxtlife.com/
    徐医生: http://blog.csdn.net/eclipsexys
    鸿洋: http://blog.csdn.net/lmj623565791/
    ImportNew: http://www.importnew.com/
    老罗: http://blog.csdn.net/luoshengyang
    邓凡平: http://blog.csdn.net/innost
    AndroidWeek: http://androidweekly.net/
    云在千峰: http://blog.chengyunfeng.com/
    哈皮小猿: http://www.cnblogs.com/wondertwo/
    Klojure: http://sixwolf.net/
    PiasyXu: http://blog.piasy.com/
    牛晓伟: http://www.jianshu.com/users/2ce7b74b592b/latest_articles
    D-clock: http://www.jianshu.com/users/ec95b5891948/latest_articles
    Gityuan: http://gityuan.com/
    MrPeak技术: http://mrpeak.cn/
    TmWork: http://lijianxinchina.github.io/
    Stay: http://notes.stay4it.com/
    Zjutkz: http://zjutkz.net/
    Mr.Monkey: http://linzh.top/
    figo: http://www.figotan.org/
    MrFu Blog: http://mrfu.me/
    C.L.Wang: http://www.wangchenlong.org/
    Jacksgong: http://blog.dreamtobe.cn/
    田维术: http://weishu.me/
    KVH: http://kvh.io/
    姚家艺: http://www.desmondyao.com/
    " ==========": #
    "========== ": #
    酷壳: http://coolshell.cn/
    阮一峰: http://www.ruanyifeng.com/blog/
    MacTalk: http://macshuo.com/
    InfoQ中文站: http://www.infoq.com/cn/
    开源中国: http://www.oschina.net/
    博客园: http://www.cnblogs.com/


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
    type: git
    repo: https://openproject@github.com/openproject/jayfeng.git
    branch: gh-pages
    # repo: https://git.coding.net/jayfeng/blog.git
    # branch: coding-pages
